force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Extracted_Data__c.field-meta.xml
<CustomField>
    <fullName>Extracted_Data__c</fullName>
    <label>Extracted Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Interview Scheduled</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JP-{000000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Posting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JobApplicationController.cls
public without sharing class JobApplicationController {
	@AuraEnabled
	public static ApplicationWrapper submitDraftApplication(ApplicationWrapper application) {
		Contact con = new Contact();
		con.FirstName = application.firstName;
		con.LastName = application.lastName;
		con.Email = application.email;
		con.Phone = application.phone;
		insert con;
		
		Job_Application__c app = new Job_Application__c();
		app.Candidate__c = con.Id;
		app.Job_Posting__c = application.jobPostingId;
		app.Status__c = 'Draft';
		insert app;

		application.applicationId = app.Id;
		application.docId = null;
		return application;
	}

	@AuraEnabled
	public static Boolean submitApplication(Id applicationId) {
		if(applicationId != null) {
			update new Job_Application__c(Id=applicationId, Status__c='Submitted');
			invokeDocumentAIApi(new List<Id> {applicationId});
			return true;
		}
		return false;
	}

	@future(callout=true)
	public static void invokeDocumentAIApi(List<Id> appIds) {
		Id appId = appIds[0];
		ContentDocumentLink cdl = [SELECT LinkedEntityId, ContentDocument.LatestPublishedVersionId 
									FROM ContentDocumentLink 
									WHERE LinkedEntityId =: appId  
									AND LinkedEntity.Type = 'Job_Application__c'
									LIMIT 1];
		System.debug('appId : ' + appId);
		String output = DocumentAIServiceJWT.callDocumentAI(cdl.ContentDocument.LatestPublishedVersionId); 
		System.debug('extracted text : ' + output);
		update new Job_Application__c(Id=appId, Extracted_Data__c=output);
	}

	public class ApplicationWrapper {
		@AuraEnabled
		public String applicationId {get; set;}
		@AuraEnabled
		public String jobPostingId {get; set;}
		@AuraEnabled
		public String firstName {get; set;}
		@AuraEnabled
		public String lastName {get; set;}
		@AuraEnabled
		public String email {get; set;}
		@AuraEnabled
		public String phone {get; set;}
		@AuraEnabled
		public String docId {get; set;}
	}
}