force-app/main/default/objects/ContentVersion/fields/Guest_Record_fileupload__c.field-meta.xml
<CustomField>
    <fullName>Guest_Record_fileupload__c</fullName>
    <label>Guest Record FileUpload</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Extracted_Data__c.field-meta.xml
<CustomField>
    <fullName>Extracted_Data__c</fullName>
    <label>Extracted Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerHandler.cls
/**
* @File Name : ContentVersionTriggerHandler.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 30, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 30, 2025 |   | Initial Version
**/

public without sharing class ContentVersionTriggerHandler {
	
	public static void afterInsert(List<ContentVersion> newList) {

		List<Id> appIds = new List<Id>();
		for(ContentVersion cv : newList) {
			if(cv.Guest_Record_fileupload__c != null) {
				appIds.add(cv.Guest_Record_fileupload__c);
			}
		}

		if(!appIds.isEmpty()) {
			invokeDocumentAIApi(appIds);
		}
	}

	@future(callout=true)
	public static void invokeDocumentAIApi(List<Id> appIds) {
		Id appId = appIds[0];
		ContentVersion cv = [SELECT Id FROM ContentVersion WHERE Guest_Record_fileupload__c =: appId ORDER BY CreatedDate DESC LIMIT 1];
		String output = DocumentAIServiceJWT.callDocumentAI(cv.Id); 
		System.debug('extracted text : ' + output);
		update new Job_Application__c(Id=appId, Extracted_Data__c=output);
		
	}
}